import fs from "node:fs";
import path from "node:path";
import { envFiles, parseEnv } from "../electron/main/env-service.js";

const root = process.cwd();
const outputPath = path.join(root, "electron/main/build-config.generated.ts");
const packageJson = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8")) as { version?: string };
const appVersion = process.env.FALLBACK_RELEASE_VERSION || packageJson.version || "0.0.0";
const clientId =
  process.env.FALLBACK_GITHUB_CLIENT_ID ||
  process.env.GITHUB_CLIENT_ID ||
  readEnvValue("FALLBACK_GITHUB_CLIENT_ID") ||
  readEnvValue("GITHUB_CLIENT_ID") ||
  "";
const updateRepository =
  process.env.FALLBACK_UPDATE_REPOSITORY ||
  process.env.GITHUB_REPOSITORY ||
  readEnvValue("FALLBACK_UPDATE_REPOSITORY") ||
  readEnvValue("GITHUB_REPOSITORY") ||
  "";

fs.writeFileSync(
  outputPath,
  `// Generated by scripts/write-build-config.ts. Do not edit by hand.
export const bundledGitHubOAuthClientId = ${JSON.stringify(clientId)};
export const fallbackAppVersion = ${JSON.stringify(appVersion)};
export const bundledFallbackUpdateRepository = ${JSON.stringify(updateRepository)};
`
);

const details = [
  clientId ? "with GitHub OAuth Client ID" : "without GitHub OAuth Client ID",
  updateRepository ? `with updater repository ${updateRepository}` : "without updater repository"
];
console.log(`Build config generated ${details.join(", ")}.`);

function readEnvValue(name: string): string | null {
  for (const file of envFiles) {
    const envPath = path.join(root, file);
    if (!fs.existsSync(envPath)) continue;
    const value = parseEnv(fs.readFileSync(envPath, "utf8")).get(name);
    if (value) return value;
  }
  return null;
}
